name: Action workflow

# on: [push, pull_request]

# We can be much more specific with our github actions based on just "general pull_request"
on:
  # pull_request:
  #   branches:
  #     - 'main'
  push:
    branches:
      - 'main'
      - 'feature/*' # matches that starts with e.g. feature/develop-branch, match feature/feat/something-branch-nanme
      - 'feature/**' # matches that starts with e.g. feature/feat/something-branch-nanme
      - '!feature/ignore-this-branch' # This will ignore this branch
    tags:
      - v1.*.*
    paths: # We would like to run only those workflow above when we change to JS file only. Nothing else works
      - '**.js'
      - '!bla-bla.js'
    # paths-ignore:
    #   - 'docs/**'
  # This is used to trigger manually by sending POST request to some URL
  # repository_dispatch:
  #   types: [build]
  # push:
  # schedule:
  # minutes, hours, day, day of a month, a month, day of the week
  # - cron: '0/5 * * * *'
  # - cron: '0/6 * * * *'
  # pull_request:
  #   types: [closed, assigned, opened, reopened]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JavaScript Action
        id: greet
        # Takes reference to an action. In this case, it's from here: https://github.com/actions/hello-world-javascript-action
        uses: actions/hello-world-javascript-action@v1.1
        # 'with' means that you can provide input to an action. The input is based on the MD documentation on the github link provided above
        with:
          who-to-greet: John Doe
      - name: Output the log of greeting time
        run: echo "${{ steps.greet.outputs.time }}"
